/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface GovernanceInterface extends Interface {
    getFunction(nameOrSignature: "approveProposal" | "emergencyPause" | "executeProposal" | "nextProposalId" | "pauseVoteCount" | "pauseVotes" | "proposalApprovals" | "proposals" | "proposeOracleChange" | "reputationRegistry" | "signers" | "timelockSeconds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyPauseTriggered" | "ProposalApproved" | "ProposalCreated" | "ProposalExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'approveProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyPause', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextProposalId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseVoteCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseVotes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'proposalApprovals', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proposeOracleChange', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'signers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'timelockSeconds', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProposalId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseVoteCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalApprovals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeOracleChange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'timelockSeconds', data: BytesLike): Result;
  }

  
    export namespace EmergencyPauseTriggeredEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalApprovedEvent {
      export type InputTuple = [proposalId: BigNumberish, approver: AddressLike];
      export type OutputTuple = [proposalId: bigint, approver: string];
      export interface OutputObject {proposalId: bigint, approver: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, newOracle: AddressLike, proposer: AddressLike];
      export type OutputTuple = [proposalId: bigint, newOracle: string, proposer: string];
      export interface OutputObject {proposalId: bigint, newOracle: string, proposer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, newOracle: AddressLike];
      export type OutputTuple = [proposalId: bigint, newOracle: string];
      export interface OutputObject {proposalId: bigint, newOracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Governance extends BaseContract {
    
    connect(runner?: ContractRunner | null): Governance;
    waitForDeployment(): Promise<this>;

    interface: GovernanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyPause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextProposalId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pauseVoteCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pauseVotes: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    proposalApprovals: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {newOracle: string, createdAt: bigint, approvalCount: bigint, executed: boolean }],
      'view'
    >
    

    
    proposeOracleChange: TypedContractMethod<
      [newOracle: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    signers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    timelockSeconds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyPause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextProposalId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseVoteCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseVotes'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalApprovals'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {newOracle: string, createdAt: bigint, approvalCount: bigint, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'proposeOracleChange'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'signers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'timelockSeconds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'EmergencyPauseTriggered'): TypedContractEvent<EmergencyPauseTriggeredEvent.InputTuple, EmergencyPauseTriggeredEvent.OutputTuple, EmergencyPauseTriggeredEvent.OutputObject>;
getEvent(key: 'ProposalApproved'): TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;

    filters: {
      
      'EmergencyPauseTriggered()': TypedContractEvent<EmergencyPauseTriggeredEvent.InputTuple, EmergencyPauseTriggeredEvent.OutputTuple, EmergencyPauseTriggeredEvent.OutputObject>;
      EmergencyPauseTriggered: TypedContractEvent<EmergencyPauseTriggeredEvent.InputTuple, EmergencyPauseTriggeredEvent.OutputTuple, EmergencyPauseTriggeredEvent.OutputObject>;
    

      'ProposalApproved(uint256,address)': TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
      ProposalApproved: TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
    

      'ProposalCreated(uint256,address,address)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256,address)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    
    };
  }