/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Governance } from './Governance.js';
export type { IReputationRegistryGov } from './IReputationRegistryGov.js';