/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentIdentityRegistry__factory } from './AgentIdentityRegistry__factory.js';
export { IReputationRegistry__factory } from './IReputationRegistry__factory.js';