/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'APIGatekeeper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.APIGatekeeper__factory>
getContractFactory(name: 'IReputationRegistryTier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationRegistryTier__factory>
getContractFactory(name: 'AgentIdentityRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentIdentityRegistry__factory>
getContractFactory(name: 'IReputationRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationRegistry__factory>
getContractFactory(name: 'Governance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Governance__factory>
getContractFactory(name: 'IReputationRegistryGov', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationRegistryGov__factory>
getContractFactory(name: 'ReputationRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReputationRegistry__factory>
getContractFactory(name: 'ValidationRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ValidationRegistry__factory>

  getContractAt(name: 'APIGatekeeper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.APIGatekeeper>
getContractAt(name: 'IReputationRegistryTier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationRegistryTier>
getContractAt(name: 'AgentIdentityRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentIdentityRegistry>
getContractAt(name: 'IReputationRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationRegistry>
getContractAt(name: 'Governance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Governance>
getContractAt(name: 'IReputationRegistryGov', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationRegistryGov>
getContractAt(name: 'ReputationRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReputationRegistry>
getContractAt(name: 'ValidationRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ValidationRegistry>

  deployContract(name: 'APIGatekeeper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.APIGatekeeper>
deployContract(name: 'IReputationRegistryTier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistryTier>
deployContract(name: 'AgentIdentityRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentIdentityRegistry>
deployContract(name: 'IReputationRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistry>
deployContract(name: 'Governance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Governance>
deployContract(name: 'IReputationRegistryGov', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistryGov>
deployContract(name: 'ReputationRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationRegistry>
deployContract(name: 'ValidationRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ValidationRegistry>

  deployContract(name: 'APIGatekeeper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.APIGatekeeper>
deployContract(name: 'IReputationRegistryTier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistryTier>
deployContract(name: 'AgentIdentityRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentIdentityRegistry>
deployContract(name: 'IReputationRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistry>
deployContract(name: 'Governance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Governance>
deployContract(name: 'IReputationRegistryGov', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationRegistryGov>
deployContract(name: 'ReputationRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationRegistry>
deployContract(name: 'ValidationRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ValidationRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  