/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReputationRegistryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "getFeedbackHistory" | "getScore" | "getTier" | "oracle" | "paused" | "setOracle" | "setPaused" | "submitFeedback" | "transferAdmin" | "usedNullifiers"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeedbackSubmitted" | "OracleUpdated" | "Paused" | "TierChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFeedbackHistory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getScore', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'setOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPaused', values: [boolean]): string;
encodeFunctionData(functionFragment: 'submitFeedback', values: [AddressLike, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usedNullifiers', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFeedbackHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFeedback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedNullifiers', data: BytesLike): Result;
  }

  
    export namespace FeedbackSubmittedEvent {
      export type InputTuple = [agent: AddressLike, nullifierHash: BytesLike, newScore: BigNumberish, newTier: BigNumberish];
      export type OutputTuple = [agent: string, nullifierHash: string, newScore: bigint, newTier: bigint];
      export interface OutputObject {agent: string, nullifierHash: string, newScore: bigint, newTier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
      export type OutputTuple = [oldOracle: string, newOracle: string];
      export interface OutputObject {oldOracle: string, newOracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [paused: boolean];
      export type OutputTuple = [paused: boolean];
      export interface OutputObject {paused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TierChangedEvent {
      export type InputTuple = [agent: AddressLike, oldTier: BigNumberish, newTier: BigNumberish];
      export type OutputTuple = [agent: string, oldTier: bigint, newTier: bigint];
      export interface OutputObject {agent: string, oldTier: bigint, newTier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationRegistry;
    waitForDeployment(): Promise<this>;

    interface: ReputationRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getFeedbackHistory: TypedContractMethod<
      [agent: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getScore: TypedContractMethod<
      [agent: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, tier: bigint, totalPayments: bigint, lastPaymentTimestamp: bigint }],
      'view'
    >
    

    
    getTier: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPaused: TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitFeedback: TypedContractMethod<
      [agent: AddressLike, nullifierHash: BytesLike, paymentWeight: BigNumberish, apiId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usedNullifiers: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getFeedbackHistory'): TypedContractMethod<
      [agent: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getScore'): TypedContractMethod<
      [agent: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, tier: bigint, totalPayments: bigint, lastPaymentTimestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTier'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaused'): TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFeedback'): TypedContractMethod<
      [agent: AddressLike, nullifierHash: BytesLike, paymentWeight: BigNumberish, apiId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usedNullifiers'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'FeedbackSubmitted'): TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'TierChanged'): TypedContractEvent<TierChangedEvent.InputTuple, TierChangedEvent.OutputTuple, TierChangedEvent.OutputObject>;

    filters: {
      
      'FeedbackSubmitted(address,bytes32,uint256,uint8)': TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
      FeedbackSubmitted: TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
    

      'OracleUpdated(address,address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'Paused(bool)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'TierChanged(address,uint8,uint8)': TypedContractEvent<TierChangedEvent.InputTuple, TierChangedEvent.OutputTuple, TierChangedEvent.OutputObject>;
      TierChanged: TypedContractEvent<TierChangedEvent.InputTuple, TierChangedEvent.OutputTuple, TierChangedEvent.OutputObject>;
    
    };
  }