/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ValidationRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addProvider" | "admin" | "authorizedProviders" | "getValidationCount" | "getValidationRate" | "submitValidation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ValidationSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'addProvider', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedProviders', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getValidationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getValidationRate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitValidation', values: [AddressLike, BytesLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'addProvider', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedProviders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getValidationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getValidationRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitValidation', data: BytesLike): Result;
  }

  
    export namespace ValidationSubmittedEvent {
      export type InputTuple = [agent: AddressLike, actionHash: BytesLike, success: boolean, provider: AddressLike];
      export type OutputTuple = [agent: string, actionHash: string, success: boolean, provider: string];
      export interface OutputObject {agent: string, actionHash: string, success: boolean, provider: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ValidationRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ValidationRegistry;
    waitForDeployment(): Promise<this>;

    interface: ValidationRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addProvider: TypedContractMethod<
      [provider: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizedProviders: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getValidationCount: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getValidationRate: TypedContractMethod<
      [agent: AddressLike, ],
      [[bigint, bigint] & {successes: bigint, total: bigint }],
      'view'
    >
    

    
    submitValidation: TypedContractMethod<
      [agent: AddressLike, actionHash: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addProvider'): TypedContractMethod<
      [provider: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedProviders'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getValidationCount'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getValidationRate'): TypedContractMethod<
      [agent: AddressLike, ],
      [[bigint, bigint] & {successes: bigint, total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'submitValidation'): TypedContractMethod<
      [agent: AddressLike, actionHash: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ValidationSubmitted'): TypedContractEvent<ValidationSubmittedEvent.InputTuple, ValidationSubmittedEvent.OutputTuple, ValidationSubmittedEvent.OutputObject>;

    filters: {
      
      'ValidationSubmitted(address,bytes32,bool,address)': TypedContractEvent<ValidationSubmittedEvent.InputTuple, ValidationSubmittedEvent.OutputTuple, ValidationSubmittedEvent.OutputObject>;
      ValidationSubmitted: TypedContractEvent<ValidationSubmittedEvent.InputTuple, ValidationSubmittedEvent.OutputTuple, ValidationSubmittedEvent.OutputObject>;
    
    };
  }