/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Governance__factory } from './Governance__factory.js';
export { IReputationRegistryGov__factory } from './IReputationRegistryGov__factory.js';