/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReputationRegistryGov, IReputationRegistryGovInterface } from "../../Governance.sol/IReputationRegistryGov.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOracle",
        "type": "address"
      }
    ],
    "name": "setOracle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "_paused",
        "type": "bool"
      }
    ],
    "name": "setPaused",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IReputationRegistryGov__factory {
    static readonly abi = _abi;
    static createInterface(): IReputationRegistryGovInterface {
      return new Interface(_abi) as IReputationRegistryGovInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReputationRegistryGov {
      return new Contract(address, _abi, runner) as unknown as IReputationRegistryGov;
    }
  }
  