/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AgentIdentityRegistryInterface extends Interface {
    getFunction(nameOrSignature: "discoverAgents" | "getAgent" | "registerAgent" | "updateMetadata"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentRegistered" | "MetadataUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'discoverAgents', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMetadata', values: [AddressLike, string]): string;

    decodeFunctionResult(functionFragment: 'discoverAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMetadata', data: BytesLike): Result;
  }

  
    export namespace AgentRegisteredEvent {
      export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, timestamp: bigint];
      export interface OutputObject {agent: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdatedEvent {
      export type InputTuple = [agent: AddressLike, metadataURI: string];
      export type OutputTuple = [agent: string, metadataURI: string];
      export interface OutputObject {agent: string, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentIdentityRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentIdentityRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentIdentityRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    discoverAgents: TypedContractMethod<
      [minTier: BigNumberish, reputationRegistry: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getAgent: TypedContractMethod<
      [agent: AddressLike, ],
      [[boolean, string, bigint] & {registered: boolean, metadataURI: string, registeredAt: bigint }],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMetadata: TypedContractMethod<
      [agent: AddressLike, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'discoverAgents'): TypedContractMethod<
      [minTier: BigNumberish, reputationRegistry: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [agent: AddressLike, ],
      [[boolean, string, bigint] & {registered: boolean, metadataURI: string, registeredAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMetadata'): TypedContractMethod<
      [agent: AddressLike, metadataURI: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'MetadataUpdated'): TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentRegistered(address,uint256)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'MetadataUpdated(address,string)': TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;
      MetadataUpdated: TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;
    
    };
  }