/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentIdentityRegistry } from './AgentIdentityRegistry.js';
export type { IReputationRegistry } from './IReputationRegistry.js';