/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReputationRegistryTier, IReputationRegistryTierInterface } from "../../APIGatekeeper.sol/IReputationRegistryTier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "getTier",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IReputationRegistryTier__factory {
    static readonly abi = _abi;
    static createInterface(): IReputationRegistryTierInterface {
      return new Interface(_abi) as IReputationRegistryTierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReputationRegistryTier {
      return new Contract(address, _abi, runner) as unknown as IReputationRegistryTier;
    }
  }
  