/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface APIGatekeeperInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "apis" | "authorizedMiddleware" | "checkAccess" | "getAPI" | "getProviderAPIs" | "nextApiId" | "providerAPIs" | "recordCall" | "registerAPI" | "reputationRegistry" | "setMiddleware"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "APICallRecorded" | "APIRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'apis', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'authorizedMiddleware', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkAccess', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAPI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProviderAPIs', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextApiId', values?: undefined): string;
encodeFunctionData(functionFragment: 'providerAPIs', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordCall', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerAPI', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMiddleware', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'apis', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedMiddleware', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAPI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProviderAPIs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextApiId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'providerAPIs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAPI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMiddleware', data: BytesLike): Result;
  }

  
    export namespace APICallRecordedEvent {
      export type InputTuple = [apiId: BigNumberish, agent: AddressLike, payment: BigNumberish];
      export type OutputTuple = [apiId: bigint, agent: string, payment: bigint];
      export interface OutputObject {apiId: bigint, agent: string, payment: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace APIRegisteredEvent {
      export type InputTuple = [apiId: BigNumberish, name: string, requiredTier: BigNumberish, pricePerCall: BigNumberish, provider: AddressLike];
      export type OutputTuple = [apiId: bigint, name: string, requiredTier: bigint, pricePerCall: bigint, provider: string];
      export interface OutputObject {apiId: bigint, name: string, requiredTier: bigint, pricePerCall: bigint, provider: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface APIGatekeeper extends BaseContract {
    
    connect(runner?: ContractRunner | null): APIGatekeeper;
    waitForDeployment(): Promise<this>;

    interface: APIGatekeeperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    apis: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, bigint, boolean] & {name: string, requiredTier: bigint, pricePerCall: bigint, provider: string, totalCalls: bigint, totalRevenue: bigint, active: boolean }],
      'view'
    >
    

    
    authorizedMiddleware: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    checkAccess: TypedContractMethod<
      [agent: AddressLike, apiId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    getAPI: TypedContractMethod<
      [apiId: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, bigint, boolean] & {name: string, requiredTier: bigint, pricePerCall: bigint, provider: string, totalCalls: bigint, totalRevenue: bigint, active: boolean }],
      'view'
    >
    

    
    getProviderAPIs: TypedContractMethod<
      [provider: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    nextApiId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    providerAPIs: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    recordCall: TypedContractMethod<
      [agent: AddressLike, apiId: BigNumberish, payment: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerAPI: TypedContractMethod<
      [requiredTier: BigNumberish, pricePerCall: BigNumberish, name: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMiddleware: TypedContractMethod<
      [middleware: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'apis'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, bigint, boolean] & {name: string, requiredTier: bigint, pricePerCall: bigint, provider: string, totalCalls: bigint, totalRevenue: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedMiddleware'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'checkAccess'): TypedContractMethod<
      [agent: AddressLike, apiId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAPI'): TypedContractMethod<
      [apiId: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, bigint, boolean] & {name: string, requiredTier: bigint, pricePerCall: bigint, provider: string, totalCalls: bigint, totalRevenue: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getProviderAPIs'): TypedContractMethod<
      [provider: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextApiId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'providerAPIs'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordCall'): TypedContractMethod<
      [agent: AddressLike, apiId: BigNumberish, payment: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerAPI'): TypedContractMethod<
      [requiredTier: BigNumberish, pricePerCall: BigNumberish, name: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMiddleware'): TypedContractMethod<
      [middleware: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'APICallRecorded'): TypedContractEvent<APICallRecordedEvent.InputTuple, APICallRecordedEvent.OutputTuple, APICallRecordedEvent.OutputObject>;
getEvent(key: 'APIRegistered'): TypedContractEvent<APIRegisteredEvent.InputTuple, APIRegisteredEvent.OutputTuple, APIRegisteredEvent.OutputObject>;

    filters: {
      
      'APICallRecorded(uint256,address,uint256)': TypedContractEvent<APICallRecordedEvent.InputTuple, APICallRecordedEvent.OutputTuple, APICallRecordedEvent.OutputObject>;
      APICallRecorded: TypedContractEvent<APICallRecordedEvent.InputTuple, APICallRecordedEvent.OutputTuple, APICallRecordedEvent.OutputObject>;
    

      'APIRegistered(uint256,string,uint8,uint256,address)': TypedContractEvent<APIRegisteredEvent.InputTuple, APIRegisteredEvent.OutputTuple, APIRegisteredEvent.OutputObject>;
      APIRegistered: TypedContractEvent<APIRegisteredEvent.InputTuple, APIRegisteredEvent.OutputTuple, APIRegisteredEvent.OutputObject>;
    
    };
  }