/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { APIGatekeeper } from './APIGatekeeper.js';
export type { IReputationRegistryTier } from './IReputationRegistryTier.js';